# Generated by Django 6.0 on 2025-12-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
