# Generated by Django 6.0 on 2026-02-04 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_article_notified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='journalist',
            new_name='author',
        ),
    ]
